### ISSUE TITLE
Fuzzy match for module names

### ISSUE THREAD

**Issue by rpglover64** [iquiw/company-ghc#13]
I'd like to be able to type something like `C.M.Re` and get `Control.Monad.Reader`. Or rather, `C.M` and have `Control.Monad` show up in the completion list.

If I understood the code correctly, this requires us not to use `all-completions`.

**Comment by iquiw** [comment]
Thanks for the suggestion.
It looks to me something like abbrev expansion rather than fuzzy match in general sense.

> If I understood the code correctly, this requires us not to use all-completions.

I think matching itself is possible with ``all-completions`` by specifying proper ``PREDICATE`` function as the 3rd argument.
But IIRC, there needs some work if inputted prefix and matched text are different.
I will check it.

**Comment by iquiw** [comment]
@rpglover64
I pushed the change to `module-prefix-match` branch.

> I'd like to be able to type something like C.M.Re and get Control.Monad.Reader. Or rather, C.M and have Control.Monad show up in the completion list.

It supports the above cases, but "C.M" matches with "Control.Monad.Reader" also.

**Comment by iquiw** [comment]
Merged to master.
Enabled by setting `company-ghc-component-prefix-match` to `t`.
